# Generated by Django 5.1.4 on 2024-12-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefone',
            old_name='usuario',
            new_name='usuario_id',
        ),
    ]
